homepage/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('experiences/', views.experiences, name='experiences'),
    path('skills/', views.skills, name='skills'),
    path('contacts/', views.contacts, name='contacts'),
    path('gallery/', views.gallery, name='gallery'),
    path('schedules/', views.schedules, name= 'schedules'),
    path('create/', views.create, name= 'create'),
    url(r'^delete/(?P<delete_id>[0-9]+)$', views.delete, name= 'delete'),
]

story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('homepage.urls')),
]

urls.py
from django.conf.urls import path
from django.urls import path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    ]

homepage/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class jadwalKegiatan(models.Model):
    nama = models.CharField(max_length = 100, default = '')
    tempat = models.CharField(max_length = 100, default = '')
    kategori = models.CharField(max_length = 100, default = '')
    hari = models.DateTimeField(default=datetime.now)
    jam = models.TimeField(default = datetime.now)

def __str__(self):
    return "{}.{}".format(self.id, self.nama)

homepage/forms.py
from django import forms
from .models import jadwalKegiatan

class ScheduleForm(forms.ModelForm):
    class Meta:
        model = jadwalKegiatan
        fields = ['nama', 'tempat', 'kategori', 'hari', 'jam']
        widgets = {
            'nama': forms.TextInput(attrs = {'class': 'form-control'}),
            'tempat': forms.TextInput(attrs = {'class': 'form-control'}),
            'kategori': forms.TextInput(attrs = {'class': 'form-control'}),
            'hari': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'jam': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control' })
        }
        labels = {
            'nama' : 'Nama Kegiatan',
        }
    

homepage/views.py
from django.shortcuts import render, redirect
from .models import jadwalKegiatan
from . import forms

# Create your views here.

def index(request):
    return render(request, 'index.html')
def experiences(request):
    return render(request, 'experiences.html')
def skills(request):
    return render(request, 'skills.html')
def contacts(request):
    return render(request, 'contacts.html')
def gallery(request):
    return render(request, 'gallery.html')
def schedules(request):
    semua_jadwal = jadwalKegiatan.objects.all()

    context = {
        'semua_jadwal': semua_jadwal,
    }
    return render(request, 'schedules.html', context)

def create(request):
    if request.method == 'POST':
        jadwal_form = forms.ScheduleForm(request.POST)
        if jadwal_form.is_valid():
            jadwal_form.save()
            return redirect('homepage:schedules')
    jadwal_form = forms.ScheduleForm()
    context = {
        'jadwal_form': jadwal_form,
    }
    return render(request, 'create.html', context)

def delete(request, delete_id):
    jadwalKegiatan.objects.filter(id=delete_id).delete()
    return redirect('homepage:schedules')

homepage/templates/contacts.html
{% extends 'menu.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html>
    <head>
        <title>Contacts</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="page4-background">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h1 id="contact">CONTACT ME</h1>
                    </div>
                </div>
                <div class="d-flex-row sub flex-wrap">
                    <div class="col-md-4 sub flex-wrap">
                        <div class="foto sub">
                            <img src="{% static 'images/gmail-logo.png' %}" alt="Gmail" height="40" width="40" class="img ml-3 mr-3">
                        </div>
                        <p class="flex-wrap" id="text">rifqihilmans21@gmail.com</p>
                    </div>
                </div>
                <div class="d-flex-row sub flex-wrap">
                    <div class="col-md-4 sub flex-wrap">
                        <div class="foto">
                            <img src="{% static 'images/instagram-logo.png' %}" alt="Instagram" height="40" width="40" class="img ml-3 mr-3" >
                        </div>
                        <p class="flex-wrap" id="text">instagram.com/rifqihilmans</p>
                    </div>
                </div>
                <div class="d-flex-row sub flex-wrap">
                    <div class="col-md-4 sub flex-wrap">
                        <div class="foto">
                            <img src="{% static 'images/twitter-logo.png' %}" alt="Twitter" height="40" width="40" class="img ml-3 mr-3">
                        </div>
                        <p class="flex-wrap" id="text">twitter.com/rifqihilmans</p>
                    </div>
                </div>
                <div class="d-flex-row sub flex-wrap">
                    <div class="col-md-4 sub flex-wrap">
                        <div class="foto">
                            <img src="{% static 'images/facebook-logo.png' %}" alt="Facebook" height="40" width="40" class="img ml-3 mr-3">
                        </div>
                        <p class="flex-wrap" id="text">facebook.com/rifqi-hilman</p>
                    </div>
                </div>
                <div class="d-flex-row sub flex-wrap">
                    <div class="col-md-4 sub flex-wrap">
                        <div class="foto">
                            <img src="{% static 'images/linkedin-logo.png' %}" alt="Linkedin" height="40" width="40" class="img ml-3 mr-3">
                        </div>
                        <p class="flex-wrap" id="text">linkedin.com/rifqi-hilman</p>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>
{% endblock %}

homepage/templates/create.html
{% extends 'menu.html' %}
{% load static %}


{% block content %}
    <div class="container-fluid page7">
        <div class="row">
            <div class="col-md-12">
                <h1 id="create">CREATE SCHEDULES</h1>
                <form method="POST" action="{% url 'homepage:create' %}">
                    {% csrf_token %}
                    {% for form in jadwal_form %}
                        <div class="form-group">
                            {{form.label}}
                            {{form}}
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-primary" value="Submit" id="button">
                </form>
            </div>
        </div>
    </div>


{% endblock %}

homepage/templates/experiences.html
{% extends 'menu.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html>
    <head>
        <title>Experiences</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="row page2">
            <div class="col-md-3">
            </div>
            <div class="col-md-6">
                <div>
                    <h1 id="experience">Experiences</h1>
                </div>
            </div>
        </div>
        <div class="row page2">
            <div class="col-md-3">
                <p>Pemira Fasilkom UI<br>as<br> Staff of Supervisory</p>
            </div>
            <div class="col-md-3">
            </div>
            <div class="col-md-3">
                <p>COMPFEST<br>as<br> Staff of Digital Marketing</p>
            </div>
            <!-- <img src="line.svg" class = "line"> -->
        </div>
        <div class="row page2">
            <div class="col-md-12">
            </div>
        </div>
        <div class="row page2">
            <div class="col-md-3">
            </div>
            <div class="col-md-3">
                <p>Computers Get Together <br>as<br> Staff of Bazaar and Food</p>
            </div>
            <div class="col-md-3">
            </div>
            <div class="col-md-3">
                <p>PMB Fasilkom UI<br>as<br> Staff of Academic Division</p>
            </div>
        </div>
    </body>
</html>
{% endblock %}

homepage/templates/gallery.html
{% extends 'menu.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html>
    <head>
        <title>Gallery</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    </head>
     <body>
        <div class="row page5">
            <div class="col-md-12">
                <h1 id="gallery">GALLERY</h1>
            </div>
        </div>
            <div class="row page5">
                <div class="col-md-4 photos">
                    <img src="{% static 'images/cgt_bazkom.jpg' %}" alt="CGT" height="300" width="400" class="img-fluid">
                </div>
                <div class="col-md-4 photos">
                    <img src="{% static 'images/compfest_dgm.jpg' %}" alt="COMPFEST" height="300" width="400" class="img-fluid">
                </div>
                <div class="col-md-4 photos">
                    <img src="{% static 'images/pemira_verpeng.jpg' %}" alt="Pemira" height="300" width="400" class="img-fluid">
                </div>
            </div>
            <div class="row page5">
                <div class="col-md-4 photos">
                    <img src="{% static 'images/pmb_akademis.jpg' %}" alt="PMB" height="300" width="400" class="img-fluid">
                </div>
                <div class="col-md-4 photos">
                    <img src="{% static 'images/compfest_dgm2.jpg' %}" alt="COMPFEST" height="300" width="400" class="img-fluid">
                </div>
                <div class="col-md-4 photos">
                    <img src="{% static 'images/cgt_bazkom2.jpg' %}" alt="CGT" height="300" width="400" class="img-fluid">
                </div>
            </div>
     </body>
</html>
{% endblock %}

homepage/templates/index.html
{% extends 'menu.html' %}
<!DOCTYPE html>
<html>
{% load static %}

{% block content %}
<head>
        <title>My Website</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
</head>
    <body>
        <div class="row">
            <div class="col-md-12">
                <div>
                    <h1 id="profile">PROFILE</h1>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div>
                    <h2 id="introduce">Hello, my name is Rifqi Hilman Saputra</h2>
                    <h2 id="introduce">I am Information System Student at University of Indonesia</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
            </div>
            <div class="col-md-6">
                <div id="photoprof">
                    <img src="{% static 'images/photo.jpg' %}" alt="Rifqi Hilman" height="250" width="250" class="rounded-circle mx-auto d-block" class="img-fluid">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
            </div>
            <div class="col-md-6">
                <div id="aboutme">
                    <p>About me</p><br>
                    <p>I am passionate on coding and design</p>
                </div>
            </div>
        </div>
    </body>
</html>
{% endblock %}

homepage/templates/menu.html
{% load static %}
<!DOCTYPE html>

<html>
    <head>
        <title>My Website</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    </head>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="nav-placeholder">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">Profile</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-link">
                    <a class="nav-link" href="/experiences" target="_blank"> Experiences</a>
                </li>
                <li class="nav-link">
                    <a class="nav-link" href="/skills" target="_blank">Skills</a>
                </li>
                <li class="nav-link">
                    <a class="nav-link" href="/contacts" target="_blank">Contacts</a>
                </li>
                <li class="nav-link">
                    <a class="nav-link" href="/gallery" target="_blank">Gallery</a>
                </li>
                <li class="nav-link dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Schedules
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/create">Create Schedules</a>
                        <a class="dropdown-item" href="/schedules">List Schedules</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% block content %}
{% endblock %}
</html>

homepage/templates/schedules.html
{% extends 'menu.html' %}
{% load static %}

{% block content %}
<body>
    <div class="row page6">
        <div class="col-md-12">
            <h1 id="schedules">SCHEDULES</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nama Kegiatan</th>
                        <th scope="col">Tempat</th>
                        <th scope="col">Kategori</th>
                        <th scope="col">Hari</th>
                        <th scope="col">Jam</th>
                        <th scope="col">Hapus</th>
                    </tr>
                </thead>
                <tbody>
                    {% for jadwal in semua_jadwal %}
                        <tr>
                            <th scope="row">{{forloop.counter}}</th>
                            <td>{{jadwal.nama}}</td>
                            <td>{{jadwal.tempat}}</td>
                            <td>{{jadwal.kategori}}</td>
                            <td>{{jadwal.hari}}</td>
                            <td>{{jadwal.jam}}</td>
                            <td><a class= "btn btn-danger"href="{% url 'homepage:delete' jadwal.id %}">Delete</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <a class = "btn btn-primary" href="{% url 'homepage:create' %}">Add Schedule</a>
        </div>
    </div>
</body>

{% endblock %}

homepage/templates/skills.html
{% extends 'menu.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html>
    <head>
        <title>Skills</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/web.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="row page3">
            <div class="col-md-12">
                <h1 id="skill">SKILLS</h1>
            </div>
        </div>
        <div class="row page3">
            <div class="col-md-4">
                <img src="{% static 'images/coding.jpg' %}" alt="coding" height="200" width="310" class="rounded" id="fotoo" class="img-fluid">
                <p id="pict">Coding</p>
            </div>
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <img src="{% static 'images/design.jpg' %}" alt="design" height="200" width="310" class="rounded" id="fotoo" class="img-fluid">
                <p id="pict">Graphic Design</p>
            </div>
        </div>
        <div class="row page3">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <img src="{% static 'images/data.jpg' %}" alt="data" height="200" width="310" class="rounded mx-auto d-block" class="img-fluid">
                <p id="pict">Data Analyst</p>
            </div>
        </div>
    </body>
</html>
{% endblock %}